version: '3.6'

services:

  db:
    container_name: dev-db
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes:
      - dev-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dev-pgdata:
    driver: local